import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import {
//   Avatar,
//   AvatarFallback,
//   AvatarImage,
// } from "@/components/ui/avatar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto">
            SAMAD PHOTO APP
            <div className="ml-auto flex items-center space-x-4">
              


            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
